from catcha_code_for_send_email import delayed_delete_confirm_code_by_email,query_database_for_confirm_code_by_email,save_data_for_confirm_code_in_table

for i in range(10):
    print(query_database_for_confirm_code_by_email)